local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.22
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["voxel_layer", "inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.35

      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 32
        max_obstacle_height: 2.0
        mark_threshold: 0
        
        # SOURCES
        observation_sources: camera1_cloud camera2_cloud

        camera1_cloud:
          topic: /zed_multi/camera1/point_cloud/cloud_registered
          data_type: "PointCloud2"
          observation_persistence: 0.0
          expected_update_rate: 0.0
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05

        camera2_cloud:
          topic: /zed_multi/camera2/point_cloud/cloud_registered
          data_type: "PointCloud2"
          observation_persistence: 0.0
          expected_update_rate: 0.0
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.22
      resolution: 0.05
      plugins: ["static_layer", "voxel_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        map_topic: "/rtabmap/map"
        subscribe_to_updates: True

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.35

      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 32
        max_obstacle_height: 2.0
        mark_threshold: 0
        
        # SOURCES
        observation_sources: camera1_cloud camera2_cloud

        camera1_cloud:
          topic: /zed_multi/camera1/point_cloud/cloud_registered
          data_type: "PointCloud2"
          observation_persistence: 0.0
          expected_update_rate: 0.0
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05

        camera2_cloud:
          topic: /zed_multi/camera2/point_cloud/cloud_registered
          data_type: "PointCloud2"
          observation_persistence: 0.0
          expected_update_rate: 0.0
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05